version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
  ssh-agent:
    image: jenkins/ssh-agent

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins: