version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
#    volumes:
#      - ./access.log:/var/log/nginx/access.log
#      - ./html:/usr/share/nginx/html
#    ports:
#      - "8080:80"